version: '3.7'

services:
  edge:
    image: ggstream.azurecr.io/ggstream-ome
    restart: always
    ports:
    - "1935:1935/tcp"
    - "3334:3334/tcp"
    - "8443:8443/tcp"
    - "9000:9000/tcp"
    - "4000-4005:4000-4005/udp"
    - "10000-10005:10000-10005/udp"
    environment:
    - OME_ORIGIN_PORT=9000
    - OME_RTMP_PROV_PORT=1935
    - OME_HLS_STREAM_PORT=8443
    - OME_DASH_STREAM_PORT=8443
    - OME_SIGNALLING_PORT=3334
    - OME_MPEGTS_PROV_PORT=4000-4005/udp
    - OME_ICE_CANDIDATES=*:10000-10005/udp
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf